meta_product_name: "Genstudent"
meta_title: "Genstudent - GET READY FOR GROWTH"
meta_description: "We connect startups with top university students."
meta_image: "chemi.jpg"
twitter_account: "@kevin"
